// <auto-generated />
using System;
using FinalExamNew.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalExamNew.Migrations.FinalExamDb
{
    [DbContext(typeof(FinalExamDbContext))]
    [Migration("20200405161728_CustomUserData2")]
    partial class CustomUserData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalExamNew.Areas.Identity.Data.FinalExamNewUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<DateTime>("DatumUclanjenja");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Ime");

                    b.Property<string>("JMBG");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Prezime");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UlicaIBroj");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("FinalExamNew.Dal.Cena", b =>
                {
                    b.Property<string>("CenaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Valuta");

                    b.Property<decimal>("Vrednost")
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("CenaId");

                    b.ToTable("Cene");
                });

            modelBuilder.Entity("FinalExamNew.Dal.KljucnaRec", b =>
                {
                    b.Property<string>("KljucnaRecId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Rec");

                    b.HasKey("KljucnaRecId");

                    b.ToTable("KljucnaRec");
                });

            modelBuilder.Entity("FinalExamNew.Dal.KljucneReciOglasa", b =>
                {
                    b.Property<string>("KljucneReciOglasaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KljucnaRecId1");

                    b.Property<string>("OglasId")
                        .IsRequired();

                    b.HasKey("KljucneReciOglasaId");

                    b.HasAlternateKey("KljucneReciOglasaId", "OglasId");

                    b.HasIndex("KljucnaRecId1");

                    b.HasIndex("OglasId");

                    b.ToTable("KljucneReciOglasa");
                });

            modelBuilder.Entity("FinalExamNew.Dal.Oglas", b =>
                {
                    b.Property<string>("OglasId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CenaId");

                    b.Property<DateTime>("DatumKreiranja");

                    b.Property<string>("Naslov");

                    b.Property<string>("Tekst");

                    b.Property<string>("UserId");

                    b.HasKey("OglasId");

                    b.HasIndex("CenaId");

                    b.HasIndex("UserId");

                    b.ToTable("Oglas");
                });

            modelBuilder.Entity("FinalExamNew.Dal.Oglasavanje", b =>
                {
                    b.Property<string>("OglasId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatumDo");

                    b.Property<DateTime>("DatumOd");

                    b.Property<string>("OglasId1");

                    b.Property<string>("OglasavanjeId")
                        .IsRequired();

                    b.Property<string>("TipOglasaId1");

                    b.HasKey("OglasId");

                    b.HasAlternateKey("OglasavanjeId", "OglasId");

                    b.HasIndex("OglasId1");

                    b.HasIndex("TipOglasaId1");

                    b.ToTable("Oglasavanje");
                });

            modelBuilder.Entity("FinalExamNew.Dal.Slika", b =>
                {
                    b.Property<string>("SlikaId");

                    b.Property<string>("OglasId");

                    b.Property<string>("AdresaSlike");

                    b.Property<string>("NaslovSlike");

                    b.Property<DateTime>("VremePostavljanjaSlike");

                    b.HasKey("SlikaId", "OglasId");

                    b.HasAlternateKey("OglasId", "SlikaId");

                    b.ToTable("Slika");
                });

            modelBuilder.Entity("FinalExamNew.Dal.TipOglasa", b =>
                {
                    b.Property<string>("TipOglasaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CenaId");

                    b.Property<string>("NazivTipaOglasa");

                    b.HasKey("TipOglasaId");

                    b.HasIndex("CenaId");

                    b.ToTable("TipOglasa");
                });

            modelBuilder.Entity("FinalExamNew.Dal.KljucneReciOglasa", b =>
                {
                    b.HasOne("FinalExamNew.Dal.KljucnaRec", "KljucnaRec")
                        .WithMany("KljucneReciOglasa")
                        .HasForeignKey("KljucnaRecId1");

                    b.HasOne("FinalExamNew.Dal.Oglas", "Oglas")
                        .WithMany("KljucneReciOglasa")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinalExamNew.Dal.Oglas", b =>
                {
                    b.HasOne("FinalExamNew.Dal.Cena", "Cena")
                        .WithMany("Oglasi")
                        .HasForeignKey("CenaId");

                    b.HasOne("FinalExamNew.Areas.Identity.Data.FinalExamNewUser", "User")
                        .WithMany("Oglasi")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FinalExamNew.Dal.Oglasavanje", b =>
                {
                    b.HasOne("FinalExamNew.Dal.Oglas", "Oglas")
                        .WithMany("Oglasavanja")
                        .HasForeignKey("OglasId1");

                    b.HasOne("FinalExamNew.Dal.TipOglasa", "TipOglasa")
                        .WithMany("Oglasavanja")
                        .HasForeignKey("TipOglasaId1");
                });

            modelBuilder.Entity("FinalExamNew.Dal.Slika", b =>
                {
                    b.HasOne("FinalExamNew.Dal.Oglas", "Oglas")
                        .WithMany("Slike")
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinalExamNew.Dal.TipOglasa", b =>
                {
                    b.HasOne("FinalExamNew.Dal.Cena", "Cena")
                        .WithMany("TipoviOglasa")
                        .HasForeignKey("CenaId");
                });
#pragma warning restore 612, 618
        }
    }
}
